In [1]:
from sklearn.datasets import load_iris

In [14]:
dataset = load_iris()
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [10]:
import pandas as pd
import numpy as np

In [15]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [29]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [30]:
dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [31]:
df['target'] = dataset.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [32]:
df['target'].value_counts().sum()

150

In [33]:
df['target'].value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [36]:
df2 = df[df['target'] != 2]

In [41]:
df2['target'].unique()

array([0, 1])

In [52]:
X = df2.iloc[:,:-1]
y = df2.iloc[:,-1]

In [46]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.20)

In [54]:
X_train.shape

(80, 4)

In [58]:
from sklearn.linear_model import LogisticRegression
classification = LogisticRegression(max_iter=200)
classification

LogisticRegression(max_iter=200)

In [56]:
import warnings
warnings.filterwarnings('ignore')

In [59]:
classification.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [60]:
y_pred = classification.predict(X_test)

In [61]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [63]:
print(confusion_matrix(y_test, y_pred))

[[12  0]
 [ 0  8]]


In [66]:
print(accuracy_score(y_test, y_pred))

1.0


In [67]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [74]:
from sklearn.model_selection import KFold, cross_val_score

In [75]:
cv = KFold(n_splits=5)

In [76]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [78]:
scores = cross_val_score(classification, X_train, y_train, cv=cv, scoring='accuracy')

In [79]:
np.mean(scores)

1.0

In [80]:
## Lets see  more complex data
## Making own data

from sklearn.datasets import make_classification

In [87]:
X, y = make_classification(n_samples=1000, n_features=10, n_redundant=5, n_informative=5, n_classes=2, random_state=1)

In [90]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.20)

In [92]:
complex_class_model = LogisticRegression(max_iter=200)
complex_class_model

LogisticRegression(max_iter=200)

In [93]:
complex_class_model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [94]:
y_pred_complex = complex_class_model.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [99]:
print(confusion_matrix(y_test, y_pred_complex))

print('--------------------------------------------------------')

print(accuracy_score(y_test, y_pred_complex))

print('-------------------------------------------------------')
print(classification_report(y_test, y_pred_complex))

[[78 13]
 [29 80]]
--------------------------------------------------------
0.79
-------------------------------------------------------
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [101]:
from sklearn.model_selection import KFold, cross_val_score

In [102]:
cv=KFold(n_splits=5)
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [103]:
score = cross_val_score(complex_class_model, X_train, y_train, cv=cv, scoring='accuracy')
score

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [104]:
np.mean(score)

0.8099999999999999