In [2]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

In [3]:
X, y = make_classification(n_samples=1000, n_features=10, n_redundant=5, n_informative=5, n_classes=3, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [5]:
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [6]:
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [7]:
y_pred = model.predict(X_test)

In [8]:
print('confusion_matrix :' )
print(confusion_matrix(y_test, y_pred))

print('--------------------------------------------------------')

print('accuracy_score :', accuracy_score(y_test, y_pred))

print('-------------------------------------------------------')
print('classification_report :')
print(classification_report(y_test, y_pred))

confusion_matrix :
[[56 16  3]
 [10 41 13]
 [17  6 38]]
--------------------------------------------------------
accuracy_score : 0.675
-------------------------------------------------------
classification_report :
              precision    recall  f1-score   support

           0       0.67      0.75      0.71        75
           1       0.65      0.64      0.65        64
           2       0.70      0.62      0.66        61

    accuracy                           0.68       200
   macro avg       0.68      0.67      0.67       200
weighted avg       0.68      0.68      0.67       200

